import { createBrowserClient } from "@supabase/ssr";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";

// ─── Environment guard ────────────────────────────────────────────────────────

export const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL ?? "";
export const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? "";

/** True when Supabase env vars are present. UI falls back to mock data when false. */
export const isSupabaseConfigured =
  SUPABASE_URL.startsWith("https://") && SUPABASE_ANON_KEY.length > 0;

/**
 * In production, mock mode (no Supabase) should never occur.
 * Log a clear warning so operators know something is wrong.
 */
if (
  typeof window !== "undefined" &&
  process.env.NEXT_PUBLIC_APP_ENV === "production" &&
  !isSupabaseConfigured
) {
  console.error(
    "[CollectBoss] CRITICAL: Running in production without Supabase configuration. " +
    "Set NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY in your environment."
  );
}

// We use an untyped SupabaseClient here because Supabase SDK's GenericTable
// constraint requires types generated by `supabase gen types typescript`.
// Our custom Database type from types.ts is used for documentation and IDE
// autocomplete in the db/* helper layer; the wrapper functions enforce safety.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type AppSupabaseClient = SupabaseClient<any>;

// ─── Browser client (singleton) ───────────────────────────────────────────────

let _browserClient: AppSupabaseClient | null = null;

export function getBrowserClient(): AppSupabaseClient | null {
  if (!isSupabaseConfigured) return null;
  if (!_browserClient) {
    _browserClient = createBrowserClient(SUPABASE_URL, SUPABASE_ANON_KEY);
  }
  return _browserClient;
}

// ─── Server client (call inside Server Components / Route Handlers) ────────────

export async function getServerClient(): Promise<AppSupabaseClient | null> {
  if (!isSupabaseConfigured) return null;

  const { createServerClient } = await import("@supabase/ssr");
  const { cookies } = await import("next/headers");
  const cookieStore = await cookies();

  return createServerClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
    cookies: {
      getAll() {
        return cookieStore.getAll();
      },
      setAll(cookiesToSet) {
        try {
          cookiesToSet.forEach(({ name, value, options }) => {
            cookieStore.set(name, value, options);
          });
        } catch {
          // Called from Server Component — ignore.
        }
      },
    },
  });
}

// ─── Service-role client (trusted server operations only) ─────────────────────

export async function getServiceClient(): Promise<AppSupabaseClient | null> {
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY ?? "";
  if (!isSupabaseConfigured || !serviceKey) return null;

  return createClient(SUPABASE_URL, serviceKey, {
    auth: { autoRefreshToken: false, persistSession: false },
  });
}
