import { createBrowserClient } from "@supabase/ssr";
import { type SupabaseClient } from "@supabase/supabase-js";

// ─── Environment guard ────────────────────────────────────────────────────────

export const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL ?? "";
export const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? "";
export const APP_URL = process.env.NEXT_PUBLIC_APP_URL?.trim() ?? "";

export type AppEnvironment = "development" | "staging" | "production";

const configuredAppEnvironment = process.env.NEXT_PUBLIC_APP_ENV;
const appEnvironmentError =
  "[CollectBoss] Blocking configuration error: NEXT_PUBLIC_APP_ENV must be development, staging, or production.";

if (
  configuredAppEnvironment &&
  configuredAppEnvironment !== "development" &&
  configuredAppEnvironment !== "staging" &&
  configuredAppEnvironment !== "production"
) {
  throw new Error(appEnvironmentError);
}

export const appEnvironment: AppEnvironment =
  (configuredAppEnvironment as AppEnvironment | undefined) ??
  (process.env.NODE_ENV === "production" ? "production" : "development");

export const isProduction = appEnvironment === "production";
export const isDeploymentEnvironment = appEnvironment !== "development";

const LOCALHOST_HOSTS = new Set(["localhost", "127.0.0.1", "::1"]);
const appUrlConfigurationError =
  "[CollectBoss] Blocking configuration error: set NEXT_PUBLIC_APP_URL to the canonical HTTPS application URL in staging or production.";

function isCanonicalAppUrl(value: string): boolean {
  if (!value) return false;

  try {
    const url = new URL(value);
    if (url.protocol !== "http:" && url.protocol !== "https:") return false;
    if (url.pathname !== "/" || url.search || url.hash) return false;
    return !isDeploymentEnvironment ||
      (url.protocol === "https:" && !LOCALHOST_HOSTS.has(url.hostname));
  } catch {
    return false;
  }
}

export const isAppUrlConfigured = isCanonicalAppUrl(APP_URL);

/**
 * Mock data is an explicit local-development opt-in. The public flag is needed
 * for browser data services; the server-only flag supports server-side demos.
 */
export const isMockDataEnabled =
  !isDeploymentEnvironment &&
  (process.env.NEXT_PUBLIC_ENABLE_MOCK_DATA === "true" ||
    (typeof window === "undefined" && process.env.ENABLE_MOCK_DATA === "true"));

/** True when the public Supabase connection settings are present and valid. */
export const isSupabaseConfigured =
  SUPABASE_URL.startsWith("https://") && SUPABASE_ANON_KEY.length > 0;

const configurationError =
  "[CollectBoss] Blocking configuration error: set NEXT_PUBLIC_SUPABASE_URL and " +
  "NEXT_PUBLIC_SUPABASE_ANON_KEY, or enable mock data explicitly for local development with " +
  "NEXT_PUBLIC_ENABLE_MOCK_DATA=true. Mock data is never allowed in staging or production.";

/**
 * Fail closed before any data service can reach its in-memory fallback.
 * Staging and production always require a real Supabase connection.
 */
if (!isSupabaseConfigured && !isMockDataEnabled) {
  throw new Error(configurationError);
}

if (isDeploymentEnvironment && !isAppUrlConfigured) {
  throw new Error(appUrlConfigurationError);
}

// We use an untyped SupabaseClient here because Supabase SDK's GenericTable
// constraint requires types generated by `supabase gen types typescript`.
// Our custom Database type from types.ts is used for documentation and IDE
// autocomplete in the db/* helper layer; the wrapper functions enforce safety.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type AppSupabaseClient = SupabaseClient<any>;

// ─── Browser client (singleton) ───────────────────────────────────────────────

let _browserClient: AppSupabaseClient | null = null;

export function getBrowserClient(): AppSupabaseClient | null {
  if (!isSupabaseConfigured) return null;
  if (!_browserClient) {
    _browserClient = createBrowserClient(SUPABASE_URL, SUPABASE_ANON_KEY);
  }
  return _browserClient;
}

// ─── Server client (call inside Server Components / Route Handlers) ────────────

// ─── Service-role client (trusted server operations only) ─────────────────────
