import type { CSSProperties } from "react";

import { brandTokens } from "../../../shared/brand-tokens.ts";

type BrandCssProperties = CSSProperties & Record<`--cb-${string}`, string>;

/** Web adapter for the shared CollectBoss Main token source. */
export const brandCssVariables: BrandCssProperties = {
  "--cb-brand-navy": brandTokens.brand.navy,
  "--cb-brand-green": brandTokens.brand.green,
  "--cb-radius-control": `${brandTokens.radius.control}px`,
  "--cb-radius-surface": `${brandTokens.radius.surface}px`,
  "--cb-background": brandTokens.background,
  "--cb-surface": brandTokens.surface.default,
  "--cb-surface-raised": brandTokens.surface.raised,
  "--cb-surface-muted": brandTokens.surface.muted,
  "--cb-surface-inverse": brandTokens.surface.inverse,
  "--cb-surface-inverse-raised": brandTokens.surface.inverseRaised,
  "--cb-overlay": brandTokens.surface.overlay,
  "--cb-text-primary": brandTokens.text.primary,
  "--cb-text-secondary": brandTokens.text.secondary,
  "--cb-text-inverse": brandTokens.text.inverse,
  "--cb-text-inverse-muted": brandTokens.text.inverseMuted,
  "--cb-text-link": brandTokens.text.link,
  "--cb-border": brandTokens.border.default,
  "--cb-divider": brandTokens.border.divider,
  "--cb-border-strong": brandTokens.border.strong,
  "--cb-border-inverse": brandTokens.border.inverse,
  "--cb-focus": brandTokens.border.focus,
  "--cb-action-primary": brandTokens.interaction.primary,
  "--cb-action-primary-hover": brandTokens.interaction.primaryHover,
  "--cb-action-primary-pressed": brandTokens.interaction.primaryPressed,
  "--cb-action-danger-hover": brandTokens.interaction.dangerHover,
  "--cb-action-danger-pressed": brandTokens.interaction.dangerPressed,
  "--cb-selected-surface": brandTokens.interaction.primarySelectedSurface,
  "--cb-selected-text": brandTokens.interaction.primarySelectedText,
  "--cb-secondary-hover": brandTokens.interaction.secondaryHover,
  "--cb-secondary-pressed": brandTokens.interaction.secondaryPressed,
  "--cb-success": brandTokens.status.success,
  "--cb-success-surface": brandTokens.status.successSurface,
  "--cb-success-border": brandTokens.status.successBorder,
  "--cb-warning": brandTokens.status.warning,
  "--cb-warning-surface": brandTokens.status.warningSurface,
  "--cb-warning-border": brandTokens.status.warningBorder,
  "--cb-danger": brandTokens.status.danger,
  "--cb-danger-strong": brandTokens.status.dangerStrong,
  "--cb-danger-surface": brandTokens.status.dangerSurface,
  "--cb-danger-border": brandTokens.status.dangerBorder,
  "--cb-information": brandTokens.status.information,
  "--cb-information-surface": brandTokens.status.informationSurface,
  "--cb-information-border": brandTokens.status.informationBorder,
  "--cb-neutral": brandTokens.status.neutral,
  "--cb-neutral-surface": brandTokens.status.neutralSurface,
  "--cb-neutral-border": brandTokens.status.neutralBorder,
  "--cb-high-risk": brandTokens.status.highRisk,
  "--cb-high-risk-surface": brandTokens.status.highRiskSurface,
  "--cb-high-risk-border": brandTokens.status.highRiskBorder,
  "--cb-disabled-surface": brandTokens.disabled.surface,
  "--cb-disabled-border": brandTokens.disabled.border,
  "--cb-disabled-text": brandTokens.disabled.text,
  "--cb-chart-1": brandTokens.chart.series1,
  "--cb-chart-2": brandTokens.chart.series2,
  "--cb-chart-3": brandTokens.chart.series3,
  "--cb-chart-4": brandTokens.chart.series4,
  "--cb-chart-5": brandTokens.chart.series5,
  "--cb-chart-grid": brandTokens.chart.grid,
  "--cb-chart-label": brandTokens.chart.label,
  "--cb-chart-tooltip": brandTokens.chart.tooltipBackground,
  "--cb-chart-tooltip-text": brandTokens.chart.tooltipText,
};

export { brandTokens };
