import { jsPDF } from "jspdf";
import type { StatementData } from "@/lib/statements/service";
import type { Statement2Data } from "@/lib/statements/service";
import { generateStatementPdfV2 } from "./statement-generator-v2.ts";
import { brandPdfColors } from "../brand/pdf-theme.ts";

const PAGE_WIDTH = 210;
const MARGIN = 15;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

function currency(value: number): string {
  return new Intl.NumberFormat("en-MY", { style: "currency", currency: "MYR" }).format(value);
}

function date(value: string): string {
  return new Date(value).toLocaleDateString("en-MY", { day: "numeric", month: "short", year: "numeric", timeZone: "UTC" });
}

function methodLabel(value: string): string {
  return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function fit(doc: jsPDF, value: string, width: number): string {
  const ellipsis = "...";
  if (doc.getTextWidth(value) <= width) return value;
  let shortened = value;
  while (shortened.length > 0 && doc.getTextWidth(`${shortened}${ellipsis}`) > width) shortened = shortened.slice(0, -1);
  return `${shortened}${ellipsis}`;
}

function generateLegacyStatementPdf(data: StatementData): Uint8Array {
  const doc = new jsPDF({ orientation: "p", unit: "mm", format: "a4" });
  let y = 18;
  let page = 1;

  function footer() {
    doc.setDrawColor(229, 231, 235);
    doc.line(MARGIN, 283, PAGE_WIDTH - MARGIN, 283);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(107, 114, 128);
    doc.text("Generated by CollectBoss from records available at generation. Verify against official payment documentation where required.", MARGIN, 288);
    doc.text(`Page ${page}`, PAGE_WIDTH - MARGIN, 288, { align: "right" });
  }

  function drawTableHeader() {
    doc.setFillColor(249, 250, 251);
    doc.rect(MARGIN, y, CONTENT_WIDTH, 7, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(6.5);
    doc.setTextColor(107, 114, 128);
    doc.text("DATE", 16, y + 4.5);
    doc.text("CASE REF", 36, y + 4.5);
    doc.text("DEBTOR / CUSTOMER", 60, y + 4.5);
    doc.text("PAYMENT REF / TYPE", 108, y + 4.5);
    doc.text("STATUS", 156, y + 4.5);
    doc.text("AMOUNT", 194, y + 4.5, { align: "right" });
    y += 7;
  }

  function nextPage() {
    footer();
    doc.addPage();
    page += 1;
    y = 18;
    drawTableHeader();
  }

  doc.setTextColor(...brandPdfColors.navy);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  const collectWidth = doc.getTextWidth("Collect");
  doc.text("Collect", MARGIN, y);
  doc.setTextColor(...brandPdfColors.green);
  doc.text("Boss", MARGIN + collectWidth, y);
  doc.setTextColor(...brandPdfColors.navy);
  y += 8;
  doc.setFontSize(13);
  doc.text("Collection Activity Statement", MARGIN, y);
  y += 7;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(75, 85, 99);
  doc.text(fit(doc, data.businessName, 100), MARGIN, y);
  doc.text(`Generated: ${date(data.generatedAt)}`, PAGE_WIDTH - MARGIN, y, { align: "right" });
  y += 5;
  doc.text(`Statement period: ${data.periodLabel}`, MARGIN, y);
  y += 10;

  const summaryRows = [
    ["TOTAL CASES", String(data.summary.totalCases)],
    ["TOTAL DUE", currency(data.summary.totalDue)],
    ["COLLECTED IN PERIOD", currency(data.summary.totalPaid)],
    ["OUTSTANDING", currency(data.summary.totalOutstanding)],
    ["PAYMENT COUNT", String(data.summary.paymentCount)],
    ["ACTIVE PLANS", String(data.summary.activePaymentPlans)],
  ];
  doc.setFillColor(240, 253, 250);
  doc.roundedRect(MARGIN, y, CONTENT_WIDTH, 30, 2, 2, "F");
  summaryRows.forEach(([label, value], index) => {
    const column = index % 3;
    const row = Math.floor(index / 3);
    const x = MARGIN + 5 + column * 59.5;
    const rowY = y + 7 + row * 14;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7);
    doc.setTextColor(6, 78, 59);
    doc.text(label, x, rowY);
    doc.setFontSize(10);
    doc.text(value, x, rowY + 6);
  });
  y += 40;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...brandPdfColors.navy);
  doc.text("Payment activity", MARGIN, y);
  y += 5;

  if (data.payments.length === 0) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(75, 85, 99);
    doc.text("No approved payment records were found for this statement period.", MARGIN, y + 6);
  } else {
    drawTableHeader();
    for (const payment of data.payments) {
      const debtor = payment.customerCompany ? `${payment.customerName} (${payment.customerCompany})` : payment.customerName;
      const paymentReference = payment.referenceNo ? `${payment.referenceNo} / ${methodLabel(payment.paymentMethod)}` : methodLabel(payment.paymentMethod);
      const rowHeight = 12;
      if (y + rowHeight > 278) nextPage();
      doc.setDrawColor(229, 231, 235);
      doc.line(MARGIN, y + rowHeight, PAGE_WIDTH - MARGIN, y + rowHeight);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7.5);
      doc.setTextColor(55, 65, 81);
      doc.text(fit(doc, date(payment.approvedAt), 18), 16, y + 5);
      doc.text(fit(doc, payment.caseReference, 21), 36, y + 5);
      doc.text(fit(doc, debtor, 45), 60, y + 5);
      doc.text(fit(doc, paymentReference, 45), 108, y + 5);
      doc.setTextColor(4, 120, 87);
      doc.text(payment.paymentStatus, 156, y + 5);
      doc.setFont("helvetica", "bold");
      doc.text(currency(payment.amount), 194, y + 5, { align: "right" });
      y += rowHeight;
    }
  }

  footer();
  return new Uint8Array(doc.output("arraybuffer"));
}

/** Preserves the original template for legacy data while routing Statement 2.0 through the new paginated template. */
export function generateStatementPdf(data: StatementData | Statement2Data): Uint8Array {
  return "version" in data && data.version === 2 ? generateStatementPdfV2(data) : generateLegacyStatementPdf(data);
}
