import {
  LegalShell, LegalH2, LegalH3, LegalP, LegalUL, LegalWarning, LegalHighlight,
} from "./legal-shell";

export function LegalDisclaimerPage() {
  return (
    <LegalShell
      title="Legal Disclaimer"
      subtitle="Important limitations and disclaimers about the CollectBoss platform."
      lastUpdated="2025-01-01"
    >
      <LegalWarning>
        CollectBoss is a software tool, not a law firm. Nothing on this platform constitutes
        legal advice. All templates, documents, and guidance are for informational purposes
        only and do not create a lawyer-client relationship.
      </LegalWarning>

      <LegalH2>1. No Legal Advice</LegalH2>
      <LegalP>
        The content, templates, guides, document drafts, small claim tutorials, formal demand
        letter generators, and any other material provided by CollectBoss are for general
        informational and organisational purposes only. They do not constitute legal advice,
        legal opinions, or legal services of any kind.
      </LegalP>
      <LegalP>
        CollectBoss is operated by a software company, not a law firm. No person associated
        with CollectBoss is acting as your solicitor, advocate, or legal representative by
        virtue of your use of this platform.
      </LegalP>
      <LegalHighlight>
        Before taking any legal action — including sending formal demand letters, filing
        claims at the Tribunal Tuntutan Pengguna Malaysia (Consumer Claims Tribunal), Small
        Claims Court, or engaging a lawyer for civil recovery — consult a qualified Malaysian
        solicitor admitted to the Malaysian Bar.
      </LegalHighlight>

      <LegalH2>2. No Guarantee of Debt Recovery</LegalH2>
      <LegalP>
        CollectBoss does not guarantee, warrant, or promise that using the platform will result
        in successful debt recovery. The outcome of any debt collection effort depends on many
        factors outside our control, including:
      </LegalP>
      <LegalUL>
        <li>The financial position and willingness of the debtor to pay</li>
        <li>The strength, completeness, and admissibility of the evidence you provide</li>
        <li>The applicable Malaysian law and jurisdiction</li>
        <li>The decisions of courts, tribunals, or mediators</li>
        <li>Factors beyond the knowledge of CollectBoss</li>
      </LegalUL>
      <LegalP>
        CollectBoss is a tool for organisation and documentation. You remain solely responsible
        for all decisions made in pursuit of debt recovery, and for the outcomes of those decisions.
      </LegalP>

      <LegalH2>3. Document Templates Are Drafts Only</LegalH2>

      <LegalH3>3.1 Formal Demand Letters</LegalH3>
      <LegalP>
        Formal demand letters generated by CollectBoss are draft templates based on general
        Malaysian commercial practice. They have not been reviewed by a Malaysian solicitor and
        are not substitutes for letters drafted or reviewed by qualified legal counsel.
        CollectBoss makes no representation as to their legal effectiveness or enforceability.
      </LegalP>

      <LegalH3>3.2 Evidence Packs</LegalH3>
      <LegalP>
        Evidence Pack PDFs compiled by CollectBoss are organisational summaries of the
        information you have uploaded. They are not legal opinions on the strength of your
        case, and their compilation does not constitute legal advice on admissibility or
        evidentiary value before any court or tribunal.
      </LegalP>

      <LegalH3>3.3 Small Claims and Tribunal Guides</LegalH3>
      <LegalP>
        Guidance provided on filing at the Consumer Claims Tribunal or Magistrates Court
        represents general publicly available information. Court rules, fee structures, and
        procedures may change. CollectBoss does not guarantee the accuracy or currency of
        this information. Always verify with the relevant court or tribunal directly.
      </LegalP>

      <LegalH3>3.4 Lawyer Referrals</LegalH3>
      <LegalP>
        Any lawyer referral feature on CollectBoss is an independent referral service.
        CollectBoss does not endorse, recommend, or warrant the quality, competence, or
        conduct of any referred legal practitioner. The lawyer-client relationship is between
        you and the lawyer only.
      </LegalP>

      <LegalH2>4. Limitation of Liability</LegalH2>
      <LegalP>
        To the maximum extent permitted by Malaysian law, CollectBoss and its officers,
        employees, contractors, and affiliates shall not be liable for:
      </LegalP>
      <LegalUL>
        <li>Any loss or damage arising from your use of, or inability to use, the platform</li>
        <li>Failure to recover any debt, including debts that are time-barred, disputed, or fraudulent</li>
        <li>Any adverse outcome from legal proceedings you initiate based on CollectBoss-generated documents</li>
        <li>Errors, inaccuracies, or omissions in platform content, templates, or guides</li>
        <li>Unauthorised access to, or loss of, your data due to events beyond our reasonable control</li>
        <li>Any consequential, indirect, special, or punitive damages of any nature</li>
      </LegalUL>
      <LegalP>
        Our total aggregate liability to you for any claim arising from use of CollectBoss
        shall not exceed the total subscription fees you paid in the 3 months immediately
        preceding the claim.
      </LegalP>

      <LegalH2>5. User Conduct and Lawful Use</LegalH2>
      <LegalP>
        Debt collection activities in Malaysia are subject to legal constraints. You are solely
        responsible for ensuring your debt collection conduct is lawful. In particular:
      </LegalP>
      <LegalUL>
        <li>
          <strong>Harassment is illegal.</strong> Repeated, threatening, or intimidating
          communications to a debtor may constitute criminal harassment or coercion under the
          Penal Code (Act 574) or other applicable laws.
        </li>
        <li>
          <strong>Third-party contact is restricted.</strong> Contacting a debtor&apos;s family,
          employer, or uninvolved third parties to pressure payment may be unlawful.
        </li>
        <li>
          <strong>Public shaming is illegal.</strong> Publicising a debtor&apos;s personal data or
          debt status on social media or public platforms without consent may violate the PDPA
          2010 and the Communications and Multimedia Act 1998.
        </li>
        <li>
          <strong>False debts are fraud.</strong> Attempting to collect fictitious, fabricated, or
          already-settled debts may constitute fraud or extortion under Malaysian law.
        </li>
      </LegalUL>
      <LegalWarning>
        CollectBoss will cooperate with Malaysian law enforcement authorities. If we receive
        credible reports of illegal debt collection conduct by a user, we may suspend the
        account and provide relevant records to authorities.
      </LegalWarning>

      <LegalH2>6. Third-Party Services</LegalH2>
      <LegalP>
        CollectBoss integrates with third-party services (Stripe, Supabase, Vercel). We are
        not responsible for the availability, accuracy, security, or conduct of these services.
        Use of these services is subject to their respective terms and privacy policies.
      </LegalP>

      <LegalH2>7. Platform Availability</LegalH2>
      <LegalP>
        CollectBoss is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis. We do not guarantee
        uninterrupted or error-free service. We reserve the right to modify, suspend, or
        discontinue the platform (or any feature) at any time with reasonable notice.
      </LegalP>

      <LegalH2>8. Governing Law</LegalH2>
      <LegalP>
        This disclaimer and all matters arising from your use of CollectBoss are governed by
        the laws of Malaysia. Any disputes shall be subject to the exclusive jurisdiction of
        the courts of Malaysia.
      </LegalP>

      <LegalH2>9. Contact</LegalH2>
      <LegalP>
        If you have questions about this disclaimer or need to report a concern, contact us
        via the{" "}
        <a href="/support" className="text-[#009966] hover:underline font-semibold">
          Support page
        </a>.
      </LegalP>
    </LegalShell>
  );
}
