import {
  LegalShell, LegalH2, LegalH3, LegalP, LegalUL, LegalWarning, LegalHighlight,
} from "./legal-shell";

export function TermsPage() {
  return (
    <LegalShell
      title="Terms of Use"
      subtitle="Please read these terms carefully before using CollectBoss."
      lastUpdated="2026-09-01"
    >
      <LegalWarning>
        CollectBoss is a software tool for debt record management. It is not a law firm
        and does not provide legal advice. Using this platform does not create a
        lawyer-client relationship. These terms are subject to Malaysian law.
      </LegalWarning>

      <LegalH2>1. Acceptance of Terms</LegalH2>
      <LegalP>
        By registering for or using CollectBoss (&ldquo;the Service&rdquo;, &ldquo;the Platform&rdquo;), you (&ldquo;User&rdquo;,
        &ldquo;you&rdquo;) agree to be bound by these Terms of Use (&ldquo;Terms&rdquo;), our Privacy Policy, and
        our Legal Disclaimer. If you do not agree, do not use the Service.
      </LegalP>
      <LegalP>
        These Terms form a binding agreement between you and CollectBoss (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;).
        We may update these Terms from time to time. Continued use of the Service after
        changes constitutes acceptance of the revised Terms.
      </LegalP>

      <LegalH2>2. Description of Service</LegalH2>
      <LegalP>
        CollectBoss is a software-as-a-service (SaaS) platform that helps Malaysian small and
        medium enterprises (SMEs) manage debt collection records, send professional reminders,
        organise evidence documents, and prepare draft legal correspondence. CollectBoss is a
        tool — it does not collect debts on your behalf.
      </LegalP>
      <LegalHighlight>
        CollectBoss does not guarantee debt recovery. The platform assists with organisation
        and documentation only. All collection actions and outcomes are the sole responsibility
        of the User.
      </LegalHighlight>

      <LegalH2>3. No Legal Advice</LegalH2>
      <LegalP>
        Nothing on CollectBoss constitutes legal advice. All document templates, demand letter
        drafts, small claim guides, and any other content generated by the platform are for
        informational purposes only. They are not a substitute for advice from a qualified
        Malaysian lawyer.
      </LegalP>
      <LegalP>
        Using this platform does not create a lawyer-client relationship between you and
        CollectBoss or any of its employees, contractors, or affiliated parties.
      </LegalP>
      <LegalP>
        Before taking legal action — including sending a formal demand letter, filing a claim
        at the Tribunal Tuntutan Pengguna Malaysia, or engaging a lawyer — you should seek
        independent legal advice from a qualified solicitor admitted to the Malaysian Bar.
      </LegalP>

      <LegalH2>4. User Obligations</LegalH2>
      <LegalH3>4.1 Accuracy of Data</LegalH3>
      <LegalP>
        You are solely responsible for the accuracy, completeness, and legality of all
        information you upload to the platform, including debtor details, invoice amounts,
        due dates, evidence files, and any other case data. CollectBoss does not verify
        or validate the accuracy of user-provided data.
      </LegalP>

      <LegalH3>4.2 Lawful Basis for Processing</LegalH3>
      <LegalP>
        By uploading personal data of third parties (debtors), you confirm that you have a
        lawful basis to do so under the Personal Data Protection Act 2010 (PDPA 2010),
        including but not limited to a legitimate business purpose such as a valid debt
        owed to your business. You must not upload personal data that you are not authorised
        to process.
      </LegalP>

      <LegalH3>4.3 Compliance with Malaysian Law</LegalH3>
      <LegalP>You agree to comply with all applicable Malaysian laws, including but not limited to:</LegalP>
      <LegalUL>
        <li>Personal Data Protection Act 2010 (PDPA 2010)</li>
        <li>Contracts Act 1950</li>
        <li>Consumer Protection Act 1999</li>
        <li>Moneylenders Act 1951 (if applicable)</li>
        <li>Communications and Multimedia Act 1998</li>
        <li>Any other applicable federal or state legislation</li>
      </LegalUL>

      <LegalH2>5. Prohibited Conduct</LegalH2>
      <LegalP>You must not use CollectBoss to:</LegalP>
      <LegalUL>
        <li>Harass, threaten, intimidate, or abuse any debtor or third party</li>
        <li>Make false, defamatory, or misleading statements about any person</li>
        <li>Publicly shame or expose debtors in violation of Malaysian law</li>
        <li>Contact a debtor&apos;s employer, family members, or uninvolved third parties to pressure
        them into paying — this may constitute unlawful harassment</li>
        <li>Upload content that is illegal, obscene, defamatory, or infringes any third-party rights</li>
        <li>Access or check a debtor&apos;s CCRIS, CTOS, or any credit bureau record without the
        debtor&apos;s prior written consent and a lawful basis to do so</li>
        <li>Attempt to collect fictitious, fabricated, or already-settled debts</li>
        <li>Use the platform to facilitate money laundering, fraud, or any criminal activity</li>
        <li>Reverse-engineer, copy, or resell any part of the platform</li>
        <li>Share your account credentials with other persons or organisations</li>
      </LegalUL>
      <LegalWarning>
        Illegal debt collection practices — including harassment, threats, and public shaming —
        are criminal offences in Malaysia. You are solely liable for your debt collection
        conduct. CollectBoss will cooperate with authorities and may suspend your account
        if illegal conduct is suspected or reported.
      </LegalWarning>

      <LegalH2>6. Subscription and Billing</LegalH2>
      <LegalP>
        CollectBoss offers Free, Starter, Boss, and Pro subscription plans. Paid plans are
        billed monthly in Ringgit Malaysia (RM) via Stripe. Prices are displayed on the
        Billing page and are subject to change with reasonable notice.
      </LegalP>
      <LegalUL>
        <li>Subscriptions renew automatically at the end of each billing period unless cancelled</li>
        <li>You may cancel at any time via the Stripe Billing Portal</li>
        <li>No refunds are issued for partial billing periods unless required by Malaysian consumer law</li>
        <li>Downgrading or cancelling will take effect at the end of the current billing period</li>
        <li>CollectBoss does not store your card details — payments are handled entirely by Stripe</li>
      </LegalUL>

      <LegalH2>7. Account Suspension and Termination</LegalH2>
      <LegalP>
        We reserve the right to suspend or terminate your account, without prior notice, if:
      </LegalP>
      <LegalUL>
        <li>You violate any of these Terms</li>
        <li>We receive credible reports of illegal or abusive conduct via the platform</li>
        <li>We are required to do so by law or court order</li>
        <li>Your account has outstanding unpaid fees</li>
        <li>Your use of the platform poses a security risk to other users</li>
      </LegalUL>

      <LegalH2>8. Intellectual Property</LegalH2>
      <LegalP>
        The CollectBoss platform, its design, codebase, templates, and branding are the
        intellectual property of CollectBoss. You are granted a limited, non-exclusive,
        non-transferable licence to use the platform for your business purposes during your
        subscription term. All other rights are reserved.
      </LegalP>
      <LegalP>
        Content you upload (case data, evidence files, etc.) remains your property. By
        uploading content, you grant CollectBoss a limited licence to store and process it
        for the purpose of providing the Service.
      </LegalP>

      <LegalH2>9. Disclaimer of Warranties</LegalH2>
      <LegalP>
        The Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind,
        express or implied, including but not limited to fitness for a particular purpose or
        uninterrupted service. We do not warrant that the platform will be error-free or that
        any specific outcome will be achieved.
      </LegalP>

      <LegalH2>10. Limitation of Liability</LegalH2>
      <LegalP>
        To the maximum extent permitted by Malaysian law, CollectBoss shall not be liable for
        any indirect, incidental, special, or consequential damages arising from your use of
        the platform, including but not limited to lost revenue, unrecovered debts, damage to
        business relationships, or legal costs.
      </LegalP>

      <LegalH2>11. Governing Law</LegalH2>
      <LegalP>
        These Terms are governed by the laws of Malaysia. Any disputes arising from these Terms
        or the use of the Service shall be subject to the exclusive jurisdiction of the courts
        of Malaysia.
      </LegalP>

      <LegalH2>12. Contact</LegalH2>
      <LegalP>
        For questions about these Terms, please contact us via the{" "}
        <a href="/support" className="text-[#009966] hover:underline font-semibold">
          Support page
        </a>.
      </LegalP>
    </LegalShell>
  );
}
