"use client";

import Link from "next/link";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useRef, useState, type ChangeEvent, type ReactNode } from "react";
import { Camera, CheckCircle2, FileImage, FileText, RefreshCcw, ScanLine, ShieldCheck, Upload } from "lucide-react";

import { formatCurrencyMinor, minorToDecimalString } from "@/lib/financial/money";
import { createJsonService } from "@/lib/pocket/client-service";
import { paymentMethodLabel, pocketPaymentMethods } from "@/lib/pocket/payments";
import { pocketConfidenceLabel } from "@/lib/pocket/receipts";
import { PocketEmptyState, PocketUnavailable } from "./pocket-states";
import { PocketStatusChip, pocketFieldClass, pocketPrimaryActionClass, pocketSecondaryActionClass } from "./pocket-ui";

const primary = pocketPrimaryActionClass;
const secondary = pocketSecondaryActionClass;
const field = pocketFieldClass;
const qualityMessages: Record<string,string> = {
  low_resolution:"The image resolution is low. Check small text carefully.", blurred:"The image may be blurred. Retake it if the text is unclear.",
  very_dark:"The image may be too dark to read clearly.", overexposed:"The image may be washed out.",
  possible_glare:"Bright areas may be glare. Check amount, date, and reference.", possibly_cropped:"Check that the full receipt is visible.",
};

const api = createJsonService({ fallbackMessage: "Something went wrong." });

type Source = "camera" | "image" | "pdf";

export function PocketReceiptCapture() {
  const router = useRouter();
  const [selection,setSelection] = useState<{file:File;source:Source;preview:string|null}|null>(null);
  const [busy,setBusy] = useState(false); const [error,setError] = useState("");
  const keyRef = useRef(crypto.randomUUID());
  useEffect(() => () => { if (selection?.preview) URL.revokeObjectURL(selection.preview); }, [selection]);
  function choose(event:ChangeEvent<HTMLInputElement>, source:Source) {
    setError(""); const file=event.target.files?.[0]; event.target.value=""; if(!file)return;
    const supported=source==="pdf" ? file.type==="application/pdf" : ["image/jpeg","image/png","image/heic","image/heif"].includes(file.type);
    if(!supported){setError("Choose a PDF, PNG, JPEG, or HEIC file that matches the selected option.");return;}
    if(file.size<=0){setError("The selected file could not be read.");return;}
    if(file.size>10*1024*1024){setError("The selected file is larger than 10 MB.");return;}
    setSelection({file,source,preview:source==="pdf"?null:URL.createObjectURL(file)});
  }
  async function upload(){if(!selection)return;setBusy(true);setError("");try{const body=new FormData();body.set("file",selection.file);body.set("source",selection.source);const result=await api<{intakeId:string}>("/api/pocket/receipts",{method:"POST",headers:{"Idempotency-Key":keyRef.current},body});router.push(`/pocket/receipts/${result.intakeId}`);router.refresh();}catch(cause){setError(cause instanceof Error?cause.message:"The receipt could not be uploaded.");}finally{setBusy(false);}}
  return <div className="mt-7 min-h-[65vh] rounded-3xl border border-emerald-950/10 bg-white p-5 shadow-sm sm:p-8">
    {!selection?<><div className="mx-auto max-w-xl text-center"><span className="mx-auto flex size-16 items-center justify-center rounded-3xl bg-emerald-50 text-[#087F5B]"><ScanLine className="size-8" aria-hidden="true"/></span><h2 className="mt-5 text-2xl font-black text-[#092F2A]">Add a payment receipt</h2><p className="mt-2 text-sm leading-6 text-slate-500">The receipt will be scanned securely. Nothing is posted until you review and confirm it.</p></div><div className="mx-auto mt-7 grid max-w-3xl gap-4 sm:grid-cols-3">
      <CaptureChoice icon={<Camera className="size-7"/>} title="Take Photo" description="Use your camera for a paper receipt." accept="image/*" capture="environment" onChange={(event)=>choose(event,"camera")}/>
      <CaptureChoice icon={<FileImage className="size-7"/>} title="Choose Image" description="Select a screenshot or saved image." accept="image/jpeg,image/png,image/heic,image/heif" onChange={(event)=>choose(event,"image")}/>
      <CaptureChoice icon={<FileText className="size-7"/>} title="Upload PDF" description="Choose a supported transaction PDF." accept="application/pdf" onChange={(event)=>choose(event,"pdf")}/>
    </div><Guidance/></>:<div className="mx-auto max-w-3xl"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><p className="text-sm font-bold text-[#087F5B]">Preview</p><h2 className="mt-1 text-xl font-black text-[#092F2A]">{selection.file.name}</h2></div><button className={secondary} onClick={()=>setSelection(null)} disabled={busy}><RefreshCcw className="mr-2 size-4"/>Replace</button></div><div className="mt-5 flex min-h-72 items-center justify-center overflow-hidden rounded-3xl bg-slate-100 p-3">{selection.preview?<Image unoptimized width={1400} height={1000} src={selection.preview} alt="Selected receipt preview" className="max-h-[55vh] h-auto max-w-full w-auto object-contain"/>:<div className="text-center text-slate-500"><FileText className="mx-auto size-14"/><p className="mt-3 font-bold">PDF selected</p><p className="mt-1 text-sm">{Math.ceil(selection.file.size/1024)} KB</p></div>}</div><Guidance/><div className="mt-6 flex flex-wrap justify-end gap-3"><button className={secondary} onClick={()=>setSelection(null)} disabled={busy}>{selection.source==="camera"?"Retake":"Choose another"}</button><button className={primary} onClick={()=>void upload()} disabled={busy}><Upload className="mr-2 size-4"/>{busy?"Uploading securely…":"Continue"}</button></div></div>}
    {error?<p role="alert" className="mx-auto mt-5 max-w-3xl rounded-2xl bg-red-50 p-4 text-sm font-semibold text-red-800">{error}</p>:null}
  </div>;
}

function CaptureChoice({icon,title,description,accept,capture,onChange}:{icon:ReactNode;title:string;description:string;accept:string;capture?:"environment";onChange:(event:ChangeEvent<HTMLInputElement>)=>void}){return <label className="flex min-h-44 cursor-pointer flex-col items-center justify-center rounded-3xl border-2 border-dashed border-emerald-900/20 p-5 text-center outline-none hover:border-[#087F5B] hover:bg-emerald-50/50 focus-within:ring-2 focus-within:ring-[#087F5B]"><span className="text-[#087F5B]">{icon}</span><span className="mt-3 font-black text-[#092F2A]">{title}</span><span className="mt-2 text-sm leading-5 text-slate-500">{description}</span><input className="sr-only" type="file" accept={accept} capture={capture} onChange={onChange}/></label>}
function Guidance(){return <div className="mx-auto mt-6 max-w-3xl rounded-2xl bg-emerald-50 p-4 text-sm leading-6 text-emerald-950"><strong>For a clearer result:</strong> keep the full receipt visible, avoid glare, and make sure the amount, date, and reference can be read.</div>}

type Candidate={candidateId:string;confidence:number};
type AmountCandidate=Candidate&{minorUnits:number;currency:string;recognizedValue:string;recommended:boolean};
type TextCandidate=Candidate&{value:string};
type ReceiptWorkspace={
  intake:{id:string;status:string}; evidence:{id:string;fileName:string;scanStatus:string;processingStatus:string;duplicateWarning:boolean;qualityWarnings:string[];hasSafePreview:boolean}|null;
  extraction:{id:string;status:string;classificationConfidence:number|null;documentKind:string|null;errorCode?:string|null}|null;
  workspace:{proposedDocumentKind:string|null;classificationConfidence:number|null;amountCandidates:AmountCandidate[];dateCandidates:TextCandidate[];referenceCandidates:TextCandidate[];bankCandidates:TextCandidate[];senderCandidates:TextCandidate[];warnings:string[];recommendedAmountCandidateId:string|null};
  latestReview:{reviewStatus:string}|null; payment:{allocation_id:string}|null; business:{defaultCurrency:string;timezone:string};
  customers:Array<{id:string;displayName:string}>;debts:Array<{id:string;customerId:string;description:string;remainingMinor:number;currency:string}>;
  customerMatches:Array<{customerId:string;displayName:string;confidence:number;strongIdentifierMatch:boolean;reasons:string[]}>;suggestedCustomer:{customerId:string;displayName:string;confidence:number;strongIdentifierMatch:boolean;reasons:string[]}|null;duplicateWarnings:string[];
};

export function PocketReceiptReview({intakeId}:{intakeId:string}){
  const router=useRouter();const[data,setData]=useState<ReceiptWorkspace|null>(null);const[error,setError]=useState("");const[busy,setBusy]=useState(false);const[reviewed,setReviewed]=useState(false);const initializedRef=useRef(false);
  const processKey=useRef(crypto.randomUUID());const reviewKey=useRef(crypto.randomUUID());const confirmKey=useRef(crypto.randomUUID());const processRequested=useRef(false);
  const[documentKind,setDocumentKind]=useState("payment_receipt");const[documentReason,setDocumentReason]=useState("");const[amount,setAmount]=useState("");const[amountCandidateId,setAmountCandidateId]=useState<string|null>(null);const[amountReason,setAmountReason]=useState("");const[paymentDate,setPaymentDate]=useState("");const[dateCandidateId,setDateCandidateId]=useState<string|null>(null);const[dateReason,setDateReason]=useState("");const[reference,setReference]=useState("");const[referenceCandidateId,setReferenceCandidateId]=useState<string|null>(null);const[referenceReason,setReferenceReason]=useState("");const[bank,setBank]=useState("");const[bankCandidateId,setBankCandidateId]=useState<string|null>(null);const[bankReason,setBankReason]=useState("");const[payerHint,setPayerHint]=useState("");const[payerCandidateId,setPayerCandidateId]=useState<string|null>(null);const[payerReason,setPayerReason]=useState("");const[customerId,setCustomerId]=useState("");const[debtId,setDebtId]=useState("");const[method,setMethod]=useState("bank_transfer");const[note,setNote]=useState("");const[duplicateAcknowledged,setDuplicateAcknowledged]=useState(false);
  function initializeReceipt(receipt:ReceiptWorkspace){if(initializedRef.current||!receipt.extraction||!["completed","needs_review"].includes(receipt.extraction.status))return;const recommended=receipt.workspace.amountCandidates.find((item)=>item.recommended)??receipt.workspace.amountCandidates[0]??null;const date=receipt.workspace.dateCandidates[0]??null;const ref=receipt.workspace.referenceCandidates[0]??null;const bankCandidate=receipt.workspace.bankCandidates[0]??null;const payer=receipt.workspace.senderCandidates[0]??null;setDocumentKind(receipt.workspace.proposedDocumentKind&&receipt.workspace.proposedDocumentKind!=="unknown_or_other"?receipt.workspace.proposedDocumentKind:"payment_receipt");if(recommended){setAmount(minorToDecimalString(BigInt(recommended.minorUnits),recommended.currency));setAmountCandidateId(recommended.candidateId);}setPaymentDate(date?.value.match(/^\d{4}-\d{2}-\d{2}/u)?.[0]??new Date().toISOString().slice(0,10));setDateCandidateId(date?.candidateId??null);setReference(ref?.value??"");setReferenceCandidateId(ref?.candidateId??null);setBank(bankCandidate?.value??"");setBankCandidateId(bankCandidate?.candidateId??null);setPayerHint(payer?.value??"");setPayerCandidateId(payer?.candidateId??null);if(receipt.suggestedCustomer?.strongIdentifierMatch)setCustomerId(receipt.suggestedCustomer.customerId);initializedRef.current=true;}
  async function load(){try{const result=await api<{receipt:ReceiptWorkspace}>(`/api/pocket/receipts/${intakeId}`);initializeReceipt(result.receipt);setData(result.receipt);if(result.receipt.payment?.allocation_id){router.replace(`/pocket/payments/${result.receipt.payment.allocation_id}`);return;}const evidence=result.receipt.evidence;const extraction=result.receipt.extraction;if(evidence?.scanStatus==="clean"&&(!extraction||extraction.status==="failed")&&!processRequested.current){processRequested.current=true;void api(`/api/pocket/receipts/${intakeId}`,{method:"POST",headers:{"Idempotency-Key":processKey.current},body:"{}"}).catch((cause)=>{processRequested.current=false;setError(cause instanceof Error?cause.message:"Processing could not start.");});}if(evidence?.scanStatus==="pending"||!extraction||["queued","processing"].includes(extraction.status))setTimeout(()=>void load(),2500);}catch(cause){setError(cause instanceof Error?cause.message:"Receipt review is unavailable.");}}
  // The polling closure intentionally resets only when the intake route changes.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{void load();return()=>{};},[intakeId]);
  const debts=useMemo(()=>data?.debts.filter((item)=>item.customerId===customerId)??[],[data,customerId]);const selectedDebt=debts.find((item)=>item.id===debtId)??null;
  async function saveReview(){if(!data)return;setBusy(true);setError("");try{await api(`/api/pocket/receipts/${intakeId}/review`,{method:"PATCH",headers:{"Idempotency-Key":reviewKey.current},body:JSON.stringify({documentKind,documentKindReason:documentReason||null,amount,amountCandidateId,amountCorrectionReason:amountReason||null,paymentDate,dateCandidateId,dateCorrectionReason:dateReason||null,reference:reference||null,referenceCandidateId,referenceCorrectionReason:referenceReason||null,bank:bank||null,bankCandidateId,bankCorrectionReason:bankReason||null,payerHint:payerHint||null,payerCandidateId,payerCorrectionReason:payerReason||null,notes:note||null})});setReviewed(true);await load();}catch(cause){const typed=cause as Error&{body?:{issues?:Array<{message:string}>}};setError(typed.body?.issues?.map((item)=>item.message).join(" ")||typed.message);}finally{setBusy(false);}}
  async function confirm(){if(!selectedDebt)return;setBusy(true);setError("");try{const result=await api<{payment:{allocationId:string}}>(`/api/pocket/receipts/${intakeId}/confirm`,{method:"POST",headers:{"Idempotency-Key":confirmKey.current},body:JSON.stringify({debtId:selectedDebt.id,expectedOutstandingMinor:selectedDebt.remainingMinor,method,note:note||null,duplicateAcknowledged})});router.push(`/pocket/payments/${result.payment.allocationId}`);router.refresh();}catch(cause){setError(cause instanceof Error?cause.message:"The payment could not be confirmed.");}finally{setBusy(false);}}
  if(error&&!data)return <PocketUnavailable/>;if(!data||!data.evidence)return <ProcessingState title="Preparing secure receipt" message="Loading the uploaded evidence…"/>;if(data.evidence.scanStatus==="quarantined"||data.evidence.scanStatus==="failed")return <ProcessingState title="Receipt unavailable" message="The security scan could not approve this file. It was not opened or processed." failed/>;if(data.evidence.scanStatus!=="clean")return <ProcessingState title="Security scan in progress" message="The original remains private while the file type and malware scan are checked."/>;if(!data.extraction||["queued","processing"].includes(data.extraction.status))return <ProcessingState title="Reading the receipt" message="The shared extraction service is finding amount, date, reference, and payer hints. No payment is being posted."/>;if(data.extraction.status==="failed")return <ProcessingState title="Could not read this receipt" message="You can safely retry processing or replace the file. No payment was posted." failed action={<button className={primary} onClick={()=>{processRequested.current=false;void load();}}>Retry Processing</button>}/>;
  const amountCandidate=data.workspace.amountCandidates.find((item)=>item.candidateId===amountCandidateId);const dateCandidate=data.workspace.dateCandidates.find((item)=>item.candidateId===dateCandidateId);const referenceCandidate=data.workspace.referenceCandidates.find((item)=>item.candidateId===referenceCandidateId);
  return <div className="mt-7 grid gap-6 lg:grid-cols-[minmax(0,0.85fr)_minmax(0,1.15fr)]"><aside className="lg:sticky lg:top-24 lg:self-start"><div className="overflow-hidden rounded-3xl border border-emerald-950/10 bg-white shadow-sm"><div className="flex items-center justify-between gap-3 p-4"><div className="min-w-0"><p className="font-black text-[#092F2A]">{data.evidence.fileName}</p><p className="text-xs font-semibold text-[#087F5B]">Private evidence · scan clean</p></div><ShieldCheck className="size-6 text-[#087F5B]"/></div><div className="min-h-80 bg-slate-100">{data.evidence.hasSafePreview?<Image unoptimized width={1400} height={1000} src={`/api/document-intakes/${intakeId}/evidence/${data.evidence.id}/preview?serve=1`} alt="Secure receipt preview" className="max-h-[65vh] h-auto w-full object-contain"/>:<iframe title="Secure receipt PDF preview" src={`/api/document-intakes/${intakeId}/evidence/${data.evidence.id}/preview?serve=1`} className="h-[60vh] w-full"/>}</div></div><Link href="/pocket/receipts/scan" className={`${secondary} mt-3 w-full`}><RefreshCcw className="mr-2 size-4"/>Replace Receipt</Link></aside><section className="rounded-3xl border border-emerald-950/10 bg-white p-5 shadow-sm sm:p-7"><p className="text-sm font-bold text-[#087F5B]">Human confirmation required</p><h2 className="mt-1 text-2xl font-black text-[#092F2A]">Check the four important fields</h2><p className="mt-2 text-sm leading-6 text-slate-500">A screenshot is evidence supplied for review, not bank verification. Nothing changes the balance until Confirm Payment.</p>{data.evidence.qualityWarnings.length?<div className="mt-5 rounded-2xl bg-amber-50 p-4 text-sm text-amber-950"><strong>Please check readability:</strong><ul className="mt-2 list-disc pl-5">{data.evidence.qualityWarnings.map((item)=><li key={item}>{qualityMessages[item]??"Review this image carefully before continuing."}</li>)}</ul></div>:null}{data.duplicateWarnings.length?<div className="mt-5 rounded-2xl bg-amber-50 p-4 text-sm text-amber-950"><strong>Possible duplicate:</strong><ul className="mt-2 list-disc pl-5">{data.duplicateWarnings.map((item)=><li key={item}>{item}</li>)}</ul></div>:null}
    <div className="mt-6 grid gap-5 sm:grid-cols-2"><PrimaryField label="Amount" confidence={pocketConfidenceLabel(amountCandidate?.confidence)}><div className="flex"><span className="mt-2 flex min-h-12 items-center rounded-l-2xl border border-r-0 border-slate-300 bg-slate-50 px-3 text-sm font-bold">{data.business.defaultCurrency}</span><input className={`${field} rounded-l-none`} inputMode="decimal" value={amount} onChange={(event)=>setAmount(event.target.value)} aria-label="Payment amount"/></div>{amountCandidate&&amount!==minorToDecimalString(BigInt(amountCandidate.minorUnits),amountCandidate.currency)?<Correction value={amountReason} onChange={setAmountReason} label="Why is the amount different?"/>:null}{data.workspace.amountCandidates.length>1?<select className={field} value={amountCandidateId??""} onChange={(event)=>{const candidate=data.workspace.amountCandidates.find((item)=>item.candidateId===event.target.value);if(candidate){setAmountCandidateId(candidate.candidateId);setAmount(minorToDecimalString(BigInt(candidate.minorUnits),candidate.currency));}}}><option value="">Enter manually</option>{data.workspace.amountCandidates.map((item)=><option key={item.candidateId} value={item.candidateId}>{formatCurrencyMinor(item.minorUnits,item.currency)} · {pocketConfidenceLabel(item.confidence)}</option>)}</select>:null}</PrimaryField><PrimaryField label="Date" confidence={pocketConfidenceLabel(dateCandidate?.confidence)}><input className={field} type="date" value={paymentDate} onChange={(event)=>setPaymentDate(event.target.value)}/>{dateCandidate&&paymentDate!==dateCandidate.value.slice(0,10)?<Correction value={dateReason} onChange={setDateReason} label="Why is the date different?"/>:null}</PrimaryField><PrimaryField label="Reference" confidence={pocketConfidenceLabel(referenceCandidate?.confidence)}><input className={field} value={reference} onChange={(event)=>setReference(event.target.value)} maxLength={255} placeholder="Optional reference"/>{referenceCandidate&&reference!==referenceCandidate.value?<Correction value={referenceReason} onChange={setReferenceReason} label="Why is the reference different?"/>:null}</PrimaryField><PrimaryField label="Suggested Customer" confidence={data.suggestedCustomer?.strongIdentifierMatch?"Looks clear":"Please check"}><select className={field} value={customerId} onChange={(event)=>{setCustomerId(event.target.value);setDebtId("");}}><option value="">Choose customer</option>{data.customers.map((item)=><option key={item.id} value={item.id}>{item.displayName}</option>)}</select>{data.suggestedCustomer?<p className="mt-2 text-xs leading-5 text-slate-500">{data.suggestedCustomer.reasons.join(" · ")}</p>:<p className="mt-2 text-xs text-slate-500">No strong identifier match was found. Choose manually.</p>}</PrimaryField></div>
    <div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold text-[#092F2A]">Target debt<select className={field} value={debtId} onChange={(event)=>setDebtId(event.target.value)} disabled={!customerId}><option value="">Choose debt</option>{debts.map((item)=><option key={item.id} value={item.id}>{item.description} · {formatCurrencyMinor(item.remainingMinor,item.currency)} remaining</option>)}</select></label><label className="text-sm font-bold text-[#092F2A]">Payment method<select className={field} value={method} onChange={(event)=>setMethod(event.target.value)}>{pocketPaymentMethods.map((item)=><option key={item} value={item}>{paymentMethodLabel(item)}</option>)}</select></label><label className="text-sm font-bold text-[#092F2A]">Bank / provider<input className={field} value={bank} onChange={(event)=>setBank(event.target.value)} placeholder="Optional"/>{data.workspace.bankCandidates[0]&&bank!==data.workspace.bankCandidates[0].value?<Correction value={bankReason} onChange={setBankReason} label="Why is the bank different?"/>:null}</label><label className="text-sm font-bold text-[#092F2A]">Sender hint<input className={field} value={payerHint} onChange={(event)=>setPayerHint(event.target.value)} placeholder="Optional"/>{data.workspace.senderCandidates[0]&&payerHint!==data.workspace.senderCandidates[0].value?<Correction value={payerReason} onChange={setPayerReason} label="Why is the sender different?"/>:null}</label></div>
    <label className="mt-5 block text-sm font-bold text-[#092F2A]">Receipt type<select className={field} value={documentKind} onChange={(event)=>setDocumentKind(event.target.value)}><option value="online_bank_transfer_receipt">Online bank transfer receipt</option><option value="transaction_screenshot">Transaction screenshot</option><option value="bank_in_cash_deposit_receipt">Bank-in / cash deposit receipt</option><option value="payment_receipt">Payment receipt</option></select></label>{data.workspace.proposedDocumentKind&&documentKind!==data.workspace.proposedDocumentKind?<Correction value={documentReason} onChange={setDocumentReason} label="Why is the receipt type different?"/>:null}<label className="mt-5 block text-sm font-bold text-[#092F2A]">Note<textarea className={`${field} min-h-24 py-3`} value={note} onChange={(event)=>setNote(event.target.value)} maxLength={1000} placeholder="Optional internal note"/></label>
    {data.duplicateWarnings.length?<label className="mt-5 flex gap-3 rounded-2xl border border-amber-200 p-4 text-sm font-semibold text-amber-950"><input type="checkbox" checked={duplicateAcknowledged} onChange={(event)=>setDuplicateAcknowledged(event.target.checked)} className="mt-1 size-4"/>I reviewed the duplicate warnings and still want to continue. A duplicate reference may still be rejected.</label>:null}
    {error?<p role="alert" className="mt-5 rounded-2xl bg-red-50 p-4 text-sm font-semibold text-red-800">{error}</p>:null}{reviewed?<div className="mt-6 rounded-2xl bg-emerald-50 p-4 text-sm text-emerald-950"><div className="flex items-center gap-2 font-black"><CheckCircle2 className="size-5"/>Reviewed and ready</div><p className="mt-2">Confirming will post {amount||"the reviewed amount"} {data.business.defaultCurrency} to the selected debt through the shared payment ledger.</p></div>:null}<div className="mt-6 flex flex-wrap justify-end gap-3">{reviewed?<button className={secondary} onClick={()=>setReviewed(false)} disabled={busy}>Edit Review</button>:null}<button className={primary} disabled={busy||!amount||!paymentDate||!customerId||!debtId||(data.duplicateWarnings.length>0&&!duplicateAcknowledged)} onClick={()=>void(reviewed?confirm():saveReview())}>{busy?"Please wait…":reviewed?"Confirm Payment":"Review Payment"}</button></div>
  </section></div>;
}

function PrimaryField({label,confidence,children}:{label:string;confidence:string;children:ReactNode}){return <label className="rounded-2xl border border-emerald-950/10 p-4 text-sm font-bold text-[#092F2A]"><span className="flex items-center justify-between gap-2"><span>{label}</span><span className={`rounded-full px-2 py-1 text-[11px] ${confidence==="Looks clear"?"bg-emerald-50 text-[#087F5B]":confidence==="Please check"?"bg-amber-50 text-amber-800":"bg-slate-100 text-slate-600"}`}>{confidence}</span></span>{children}</label>}
function Correction({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <input className={`${field} text-sm`} value={value} onChange={(event)=>onChange(event.target.value)} placeholder={label} maxLength={500}/>}
function ProcessingState({title,message,failed=false,action}:{title:string;message:string;failed?:boolean;action?:ReactNode}){return <div className="mx-auto mt-10 max-w-xl rounded-3xl border border-emerald-950/10 bg-white p-8 text-center shadow-sm"><span className={`mx-auto flex size-16 items-center justify-center rounded-3xl ${failed?"bg-amber-50 text-amber-700":"bg-emerald-50 text-[#087F5B]"}`}>{failed?<FileText className="size-8"/>:<ScanLine className="size-8 animate-pulse motion-reduce:animate-none"/>}</span><h2 className="mt-5 text-2xl font-black text-[#092F2A]">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{message}</p>{action?<div className="mt-5">{action}</div>:null}</div>}

type ReceiptListItem={intakeId:string;status:string;fileName:string;scanStatus:string|null;processingStatus:string|null;duplicateWarning:boolean;allocationId:string|null;updatedAt:string};
export function PocketReceiptList(){const[data,setData]=useState<ReceiptListItem[]|null>(null);const[failed,setFailed]=useState(false);useEffect(()=>{void api<{receipts:ReceiptListItem[]}>("/api/pocket/receipts").then((result)=>setData(result.receipts)).catch(()=>setFailed(true));},[]);if(failed)return <PocketUnavailable/>;if(!data)return <ProcessingState title="Loading receipts" message="Opening your private receipt history…"/>;if(!data.length)return <PocketEmptyState title="No receipts yet" message="Scan a payment receipt to reduce typing while keeping confirmation in your control." action={<Link href="/pocket/receipts/scan" className={primary}>Scan Receipt</Link>}/>;return <div className="mt-7 space-y-3">{data.map((item)=>{const label=item.status==="confirmed"?"Payment confirmed":item.scanStatus==="pending"?"Scanning":item.processingStatus==="processing"?"Reading":"Review";return <Link key={item.intakeId} href={item.allocationId?`/pocket/payments/${item.allocationId}`:`/pocket/receipts/${item.intakeId}`} className="pocket-card flex items-center justify-between gap-4 p-5"><span className="min-w-0"><span className="block font-black text-[#092F2A]">{item.fileName}</span><span className="mt-1 block text-sm text-slate-500">{item.duplicateWarning?"Duplicate review needed · ":""}{new Date(item.updatedAt).toLocaleDateString()}</span></span><PocketStatusChip label={label} tone={item.status==="confirmed"?"success":item.duplicateWarning?"warning":"neutral"}/></Link>;})}</div>}
